// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	encryption "github.com/vilasle/gokeep/internal/encryption"
	service "github.com/vilasle/gokeep/internal/service"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// GetSessionByCredentialToken mocks base method.
func (m *MockAuthService) GetSessionByCredentialToken(ctx context.Context, token string) (service.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByCredentialToken", ctx, token)
	ret0, _ := ret[0].(service.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByCredentialToken indicates an expected call of GetSessionByCredentialToken.
func (mr *MockAuthServiceMockRecorder) GetSessionByCredentialToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByCredentialToken", reflect.TypeOf((*MockAuthService)(nil).GetSessionByCredentialToken), ctx, token)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, req service.RegisterLoginUser) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, req)
}

// Register mocks base method.
func (m *MockAuthService) Register(ctx context.Context, req service.RegisterLoginUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), ctx, req)
}

// MockPrivateDataService is a mock of PrivateDataService interface.
type MockPrivateDataService struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataServiceMockRecorder
}

// MockPrivateDataServiceMockRecorder is the mock recorder for MockPrivateDataService.
type MockPrivateDataServiceMockRecorder struct {
	mock *MockPrivateDataService
}

// NewMockPrivateDataService creates a new mock instance.
func NewMockPrivateDataService(ctrl *gomock.Controller) *MockPrivateDataService {
	mock := &MockPrivateDataService{ctrl: ctrl}
	mock.recorder = &MockPrivateDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataService) EXPECT() *MockPrivateDataServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPrivateDataService) Delete(ctx context.Context, req service.DeletePrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPrivateDataServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrivateDataService)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockPrivateDataService) Get(ctx context.Context, req service.GetPrivateData) (service.PrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(service.PrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPrivateDataServiceMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrivateDataService)(nil).Get), ctx, req)
}

// List mocks base method.
func (m *MockPrivateDataService) List(ctx context.Context, userID int) (service.ListPrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(service.ListPrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPrivateDataServiceMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPrivateDataService)(nil).List), ctx, userID)
}

// MockLoginPasswordService is a mock of LoginPasswordService interface.
type MockLoginPasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockLoginPasswordServiceMockRecorder
}

// MockLoginPasswordServiceMockRecorder is the mock recorder for MockLoginPasswordService.
type MockLoginPasswordServiceMockRecorder struct {
	mock *MockLoginPasswordService
}

// NewMockLoginPasswordService creates a new mock instance.
func NewMockLoginPasswordService(ctrl *gomock.Controller) *MockLoginPasswordService {
	mock := &MockLoginPasswordService{ctrl: ctrl}
	mock.recorder = &MockLoginPasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginPasswordService) EXPECT() *MockLoginPasswordServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockLoginPasswordService) Add(ctx context.Context, req service.AddLoginPassword, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockLoginPasswordServiceMockRecorder) Add(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockLoginPasswordService)(nil).Add), ctx, req, clientKey)
}

// Delete mocks base method.
func (m *MockLoginPasswordService) Delete(ctx context.Context, req service.DeletePrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLoginPasswordServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoginPasswordService)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockLoginPasswordService) Get(ctx context.Context, req service.GetPrivateData) (service.PrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(service.PrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLoginPasswordServiceMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLoginPasswordService)(nil).Get), ctx, req)
}

// List mocks base method.
func (m *MockLoginPasswordService) List(ctx context.Context, userID int) (service.ListPrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(service.ListPrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLoginPasswordServiceMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLoginPasswordService)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockLoginPasswordService) Update(ctx context.Context, req service.UpdateLoginPassword, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLoginPasswordServiceMockRecorder) Update(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoginPasswordService)(nil).Update), ctx, req, clientKey)
}

// MockBankCardService is a mock of BankCardService interface.
type MockBankCardService struct {
	ctrl     *gomock.Controller
	recorder *MockBankCardServiceMockRecorder
}

// MockBankCardServiceMockRecorder is the mock recorder for MockBankCardService.
type MockBankCardServiceMockRecorder struct {
	mock *MockBankCardService
}

// NewMockBankCardService creates a new mock instance.
func NewMockBankCardService(ctrl *gomock.Controller) *MockBankCardService {
	mock := &MockBankCardService{ctrl: ctrl}
	mock.recorder = &MockBankCardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankCardService) EXPECT() *MockBankCardServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBankCardService) Add(ctx context.Context, req service.AddBankCard, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBankCardServiceMockRecorder) Add(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBankCardService)(nil).Add), ctx, req, clientKey)
}

// Delete mocks base method.
func (m *MockBankCardService) Delete(ctx context.Context, req service.DeletePrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBankCardServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBankCardService)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockBankCardService) Get(ctx context.Context, req service.GetPrivateData) (service.PrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(service.PrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBankCardServiceMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBankCardService)(nil).Get), ctx, req)
}

// List mocks base method.
func (m *MockBankCardService) List(ctx context.Context, userID int) (service.ListPrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(service.ListPrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBankCardServiceMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBankCardService)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockBankCardService) Update(ctx context.Context, req service.UpdateBankCard, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBankCardServiceMockRecorder) Update(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBankCardService)(nil).Update), ctx, req, clientKey)
}

// MockTextDataService is a mock of TextDataService interface.
type MockTextDataService struct {
	ctrl     *gomock.Controller
	recorder *MockTextDataServiceMockRecorder
}

// MockTextDataServiceMockRecorder is the mock recorder for MockTextDataService.
type MockTextDataServiceMockRecorder struct {
	mock *MockTextDataService
}

// NewMockTextDataService creates a new mock instance.
func NewMockTextDataService(ctrl *gomock.Controller) *MockTextDataService {
	mock := &MockTextDataService{ctrl: ctrl}
	mock.recorder = &MockTextDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextDataService) EXPECT() *MockTextDataServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTextDataService) Add(ctx context.Context, req service.AddTextData, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTextDataServiceMockRecorder) Add(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTextDataService)(nil).Add), ctx, req, clientKey)
}

// Delete mocks base method.
func (m *MockTextDataService) Delete(ctx context.Context, req service.DeletePrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTextDataServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTextDataService)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockTextDataService) Get(ctx context.Context, req service.GetPrivateData) (service.PrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(service.PrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTextDataServiceMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTextDataService)(nil).Get), ctx, req)
}

// List mocks base method.
func (m *MockTextDataService) List(ctx context.Context, userID int) (service.ListPrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(service.ListPrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTextDataServiceMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTextDataService)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockTextDataService) Update(ctx context.Context, req service.UpdateTextData, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTextDataServiceMockRecorder) Update(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTextDataService)(nil).Update), ctx, req, clientKey)
}

// MockBinaryDataService is a mock of BinaryDataService interface.
type MockBinaryDataService struct {
	ctrl     *gomock.Controller
	recorder *MockBinaryDataServiceMockRecorder
}

// MockBinaryDataServiceMockRecorder is the mock recorder for MockBinaryDataService.
type MockBinaryDataServiceMockRecorder struct {
	mock *MockBinaryDataService
}

// NewMockBinaryDataService creates a new mock instance.
func NewMockBinaryDataService(ctrl *gomock.Controller) *MockBinaryDataService {
	mock := &MockBinaryDataService{ctrl: ctrl}
	mock.recorder = &MockBinaryDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinaryDataService) EXPECT() *MockBinaryDataServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBinaryDataService) Add(ctx context.Context, req service.AddBinaryData, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBinaryDataServiceMockRecorder) Add(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBinaryDataService)(nil).Add), ctx, req, clientKey)
}

// Delete mocks base method.
func (m *MockBinaryDataService) Delete(ctx context.Context, req service.DeletePrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBinaryDataServiceMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBinaryDataService)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockBinaryDataService) Get(ctx context.Context, req service.GetPrivateData) (service.PrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(service.PrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBinaryDataServiceMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBinaryDataService)(nil).Get), ctx, req)
}

// List mocks base method.
func (m *MockBinaryDataService) List(ctx context.Context, userID int) (service.ListPrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].(service.ListPrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBinaryDataServiceMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBinaryDataService)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockBinaryDataService) Update(ctx context.Context, req service.UpdateBinaryData, clientKey encryption.Encoder) (service.AddingUpdatePrivateDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, clientKey)
	ret0, _ := ret[0].(service.AddingUpdatePrivateDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBinaryDataServiceMockRecorder) Update(ctx, req, clientKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBinaryDataService)(nil).Update), ctx, req, clientKey)
}
