// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/encryption.go

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncrypter is a mock of Encrypter interface.
type MockEncrypter struct {
	ctrl     *gomock.Controller
	recorder *MockEncrypterMockRecorder
}

// MockEncrypterMockRecorder is the mock recorder for MockEncrypter.
type MockEncrypterMockRecorder struct {
	mock *MockEncrypter
}

// NewMockEncrypter creates a new mock instance.
func NewMockEncrypter(ctrl *gomock.Controller) *MockEncrypter {
	mock := &MockEncrypter{ctrl: ctrl}
	mock.recorder = &MockEncrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncrypter) EXPECT() *MockEncrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncrypter) Decrypt(arg0 EncryptedData) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncrypterMockRecorder) Decrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncrypter)(nil).Decrypt), arg0)
}

// DecryptKey mocks base method.
func (m *MockEncrypter) DecryptKey(arg0 []byte) (*EncryptedData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptKey", arg0)
	ret0, _ := ret[0].(*EncryptedData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptKey indicates an expected call of DecryptKey.
func (mr *MockEncrypterMockRecorder) DecryptKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptKey", reflect.TypeOf((*MockEncrypter)(nil).DecryptKey), arg0)
}

// Encrypt mocks base method.
func (m *MockEncrypter) Encrypt(arg0 []byte) (*EncryptedData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].(*EncryptedData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncrypterMockRecorder) Encrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncrypter)(nil).Encrypt), arg0)
}

// EncryptKey mocks base method.
func (m *MockEncrypter) EncryptKey(arg0 EncryptedData) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptKey", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptKey indicates an expected call of EncryptKey.
func (mr *MockEncrypterMockRecorder) EncryptKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptKey", reflect.TypeOf((*MockEncrypter)(nil).EncryptKey), arg0)
}
