// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/repository.go

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vilasle/gokeep/internal/model"
)

// MockRepositoryCollector is a mock of RepositoryCollector interface.
type MockRepositoryCollector struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryCollectorMockRecorder
}

// MockRepositoryCollectorMockRecorder is the mock recorder for MockRepositoryCollector.
type MockRepositoryCollectorMockRecorder struct {
	mock *MockRepositoryCollector
}

// NewMockRepositoryCollector creates a new mock instance.
func NewMockRepositoryCollector(ctrl *gomock.Controller) *MockRepositoryCollector {
	mock := &MockRepositoryCollector{ctrl: ctrl}
	mock.recorder = &MockRepositoryCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryCollector) EXPECT() *MockRepositoryCollectorMockRecorder {
	return m.recorder
}

// Private mocks base method.
func (m *MockRepositoryCollector) Private() model.PrivateDataRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Private")
	ret0, _ := ret[0].(model.PrivateDataRepository)
	return ret0
}

// Private indicates an expected call of Private.
func (mr *MockRepositoryCollectorMockRecorder) Private() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Private", reflect.TypeOf((*MockRepositoryCollector)(nil).Private))
}

// User mocks base method.
func (m *MockRepositoryCollector) User() model.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(model.UserRepository)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockRepositoryCollectorMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockRepositoryCollector)(nil).User))
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserRepository) Add(arg0 context.Context, arg1 model.UserAdd) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockUserRepositoryMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserRepository)(nil).Add), arg0, arg1)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), arg0, arg1)
}

// Find mocks base method.
func (m *MockUserRepository) Find(arg0 context.Context, arg1 string) (model.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(model.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserRepository)(nil).Find), arg0, arg1)
}

// Get mocks base method.
func (m *MockUserRepository) Get(arg0 context.Context, arg1 int) (model.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(model.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepository)(nil).Get), arg0, arg1)
}

// Update mocks base method.
func (m *MockUserRepository) Update(arg0 context.Context, arg1 model.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), arg0, arg1)
}

// MockPrivateData is a mock of PrivateData interface.
type MockPrivateData struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataMockRecorder
}

// MockPrivateDataMockRecorder is the mock recorder for MockPrivateData.
type MockPrivateDataMockRecorder struct {
	mock *MockPrivateData
}

// NewMockPrivateData creates a new mock instance.
func NewMockPrivateData(ctrl *gomock.Controller) *MockPrivateData {
	mock := &MockPrivateData{ctrl: ctrl}
	mock.recorder = &MockPrivateDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateData) EXPECT() *MockPrivateDataMockRecorder {
	return m.recorder
}

// EncryptedData mocks base method.
func (m *MockPrivateData) EncryptedData() model.EncryptedData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptedData")
	ret0, _ := ret[0].(model.EncryptedData)
	return ret0
}

// EncryptedData indicates an expected call of EncryptedData.
func (mr *MockPrivateDataMockRecorder) EncryptedData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptedData", reflect.TypeOf((*MockPrivateData)(nil).EncryptedData))
}

// ID mocks base method.
func (m *MockPrivateData) ID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(int)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockPrivateDataMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockPrivateData)(nil).ID))
}

// Metadata mocks base method.
func (m *MockPrivateData) Metadata() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockPrivateDataMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockPrivateData)(nil).Metadata))
}

// Owner mocks base method.
func (m *MockPrivateData) Owner() model.UserAccess {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owner")
	ret0, _ := ret[0].(model.UserAccess)
	return ret0
}

// Owner indicates an expected call of Owner.
func (mr *MockPrivateDataMockRecorder) Owner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owner", reflect.TypeOf((*MockPrivateData)(nil).Owner))
}

// String mocks base method.
func (m *MockPrivateData) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockPrivateDataMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockPrivateData)(nil).String))
}

// Type mocks base method.
func (m *MockPrivateData) Type() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(int)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPrivateDataMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPrivateData)(nil).Type))
}

// MockPrivateDataRepository is a mock of PrivateDataRepository interface.
type MockPrivateDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataRepositoryMockRecorder
}

// MockPrivateDataRepositoryMockRecorder is the mock recorder for MockPrivateDataRepository.
type MockPrivateDataRepositoryMockRecorder struct {
	mock *MockPrivateDataRepository
}

// NewMockPrivateDataRepository creates a new mock instance.
func NewMockPrivateDataRepository(ctrl *gomock.Controller) *MockPrivateDataRepository {
	mock := &MockPrivateDataRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataRepository) EXPECT() *MockPrivateDataRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPrivateDataRepository) Add(ctx context.Context, data model.PrivateDataSave) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockPrivateDataRepositoryMockRecorder) Add(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPrivateDataRepository)(nil).Add), ctx, data)
}

// Delete mocks base method.
func (m *MockPrivateDataRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPrivateDataRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrivateDataRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockPrivateDataRepository) Get(arg0 context.Context, arg1 int) (model.PrivateDataInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(model.PrivateDataInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPrivateDataRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrivateDataRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockPrivateDataRepository) List(ctx context.Context, modelType model.Type, userID int) ([]model.PrivateDataInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, modelType, userID)
	ret0, _ := ret[0].([]model.PrivateDataInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPrivateDataRepositoryMockRecorder) List(ctx, modelType, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPrivateDataRepository)(nil).List), ctx, modelType, userID)
}

// Update mocks base method.
func (m *MockPrivateDataRepository) Update(ctx context.Context, data model.PrivateDataSave) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPrivateDataRepositoryMockRecorder) Update(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPrivateDataRepository)(nil).Update), ctx, data)
}
