// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/user.go

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserAccess is a mock of UserAccess interface.
type MockUserAccess struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccessMockRecorder
}

// MockUserAccessMockRecorder is the mock recorder for MockUserAccess.
type MockUserAccessMockRecorder struct {
	mock *MockUserAccess
}

// NewMockUserAccess creates a new mock instance.
func NewMockUserAccess(ctrl *gomock.Controller) *MockUserAccess {
	mock := &MockUserAccess{ctrl: ctrl}
	mock.recorder = &MockUserAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccess) EXPECT() *MockUserAccessMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockUserAccess) Hash() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash")
	ret0, _ := ret[0].(string)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockUserAccessMockRecorder) Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockUserAccess)(nil).Hash))
}

// ID mocks base method.
func (m *MockUserAccess) ID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(int)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockUserAccessMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockUserAccess)(nil).ID))
}

// Login mocks base method.
func (m *MockUserAccess) Login() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login")
	ret0, _ := ret[0].(string)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockUserAccessMockRecorder) Login() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserAccess)(nil).Login))
}

// PasswordIsValid mocks base method.
func (m *MockUserAccess) PasswordIsValid(password string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordIsValid", password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PasswordIsValid indicates an expected call of PasswordIsValid.
func (mr *MockUserAccessMockRecorder) PasswordIsValid(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordIsValid", reflect.TypeOf((*MockUserAccess)(nil).PasswordIsValid), password)
}
