// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/client.go

// Package cmd is a generated GoMock package.
package cmd

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// CreateAccount mocks base method.
func (m *MockClient) CreateAccount(ctx context.Context, accountName, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, accountName, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockClientMockRecorder) CreateAccount(ctx, accountName, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockClient)(nil).CreateAccount), ctx, accountName, password)
}

// DeleteBankCard mocks base method.
func (m *MockClient) DeleteBankCard(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankCard", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankCard indicates an expected call of DeleteBankCard.
func (mr *MockClientMockRecorder) DeleteBankCard(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankCard", reflect.TypeOf((*MockClient)(nil).DeleteBankCard), ctx, id)
}

// DeleteBinaryData mocks base method.
func (m *MockClient) DeleteBinaryData(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinaryData", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinaryData indicates an expected call of DeleteBinaryData.
func (mr *MockClientMockRecorder) DeleteBinaryData(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinaryData", reflect.TypeOf((*MockClient)(nil).DeleteBinaryData), ctx, id)
}

// DeleteLoginPassword mocks base method.
func (m *MockClient) DeleteLoginPassword(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoginPassword", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoginPassword indicates an expected call of DeleteLoginPassword.
func (mr *MockClientMockRecorder) DeleteLoginPassword(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoginPassword", reflect.TypeOf((*MockClient)(nil).DeleteLoginPassword), ctx, id)
}

// DeleteTextData mocks base method.
func (m *MockClient) DeleteTextData(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTextData", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTextData indicates an expected call of DeleteTextData.
func (mr *MockClientMockRecorder) DeleteTextData(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTextData", reflect.TypeOf((*MockClient)(nil).DeleteTextData), ctx, id)
}

// GetBankCard mocks base method.
func (m *MockClient) GetBankCard(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankCard", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetBankCard indicates an expected call of GetBankCard.
func (mr *MockClientMockRecorder) GetBankCard(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankCard", reflect.TypeOf((*MockClient)(nil).GetBankCard), ctx, id)
}

// GetBinaryData mocks base method.
func (m *MockClient) GetBinaryData(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinaryData", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetBinaryData indicates an expected call of GetBinaryData.
func (mr *MockClientMockRecorder) GetBinaryData(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinaryData", reflect.TypeOf((*MockClient)(nil).GetBinaryData), ctx, id)
}

// GetLoginPassword mocks base method.
func (m *MockClient) GetLoginPassword(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginPassword", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetLoginPassword indicates an expected call of GetLoginPassword.
func (mr *MockClientMockRecorder) GetLoginPassword(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginPassword", reflect.TypeOf((*MockClient)(nil).GetLoginPassword), ctx, id)
}

// GetTextData mocks base method.
func (m *MockClient) GetTextData(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextData", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetTextData indicates an expected call of GetTextData.
func (mr *MockClientMockRecorder) GetTextData(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextData", reflect.TypeOf((*MockClient)(nil).GetTextData), ctx, id)
}

// Login mocks base method.
func (m *MockClient) Login(ctx context.Context, accountName, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, accountName, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockClientMockRecorder) Login(ctx, accountName, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClient)(nil).Login), ctx, accountName, password)
}

// SaveBankCard mocks base method.
func (m *MockClient) SaveBankCard(ctx context.Context, number, expires string, cvv, id int, meta map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBankCard", ctx, number, expires, cvv, id, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBankCard indicates an expected call of SaveBankCard.
func (mr *MockClientMockRecorder) SaveBankCard(ctx, number, expires, cvv, id, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBankCard", reflect.TypeOf((*MockClient)(nil).SaveBankCard), ctx, number, expires, cvv, id, meta)
}

// SaveBinaryData mocks base method.
func (m *MockClient) SaveBinaryData(ctx context.Context, content []byte, name string, id int, meta map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBinaryData", ctx, content, name, id, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBinaryData indicates an expected call of SaveBinaryData.
func (mr *MockClientMockRecorder) SaveBinaryData(ctx, content, name, id, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBinaryData", reflect.TypeOf((*MockClient)(nil).SaveBinaryData), ctx, content, name, id, meta)
}

// SaveLoginPassword mocks base method.
func (m *MockClient) SaveLoginPassword(ctx context.Context, login, password string, id int, meta map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLoginPassword", ctx, login, password, id, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLoginPassword indicates an expected call of SaveLoginPassword.
func (mr *MockClientMockRecorder) SaveLoginPassword(ctx, login, password, id, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLoginPassword", reflect.TypeOf((*MockClient)(nil).SaveLoginPassword), ctx, login, password, id, meta)
}

// SaveTextData mocks base method.
func (m *MockClient) SaveTextData(ctx context.Context, text, name string, id int, meta map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTextData", ctx, text, name, id, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTextData indicates an expected call of SaveTextData.
func (mr *MockClientMockRecorder) SaveTextData(ctx, text, name, id, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTextData", reflect.TypeOf((*MockClient)(nil).SaveTextData), ctx, text, name, id, meta)
}

// Sync mocks base method.
func (m *MockClient) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockClientMockRecorder) Sync(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockClient)(nil).Sync), ctx)
}
