// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_CreateAccount_FullMethodName = "/proto.AccountService/CreateAccount"
	AccountService_Login_FullMethodName         = "/proto.AccountService/Login"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AccountService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
type AccountServiceServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AccountService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	PrivateDataService_SaveLoginPassword_FullMethodName = "/proto.PrivateDataService/SaveLoginPassword"
	PrivateDataService_SaveBankCard_FullMethodName      = "/proto.PrivateDataService/SaveBankCard"
	PrivateDataService_SaveTextData_FullMethodName      = "/proto.PrivateDataService/SaveTextData"
	PrivateDataService_SaveBinaryData_FullMethodName    = "/proto.PrivateDataService/SaveBinaryData"
	PrivateDataService_Delete_FullMethodName            = "/proto.PrivateDataService/Delete"
)

// PrivateDataServiceClient is the client API for PrivateDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivateDataServiceClient interface {
	SaveLoginPassword(ctx context.Context, in *SaveLoginPasswordRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error)
	SaveBankCard(ctx context.Context, in *SaveBankCardRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error)
	SaveTextData(ctx context.Context, in *SaveTextDataRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error)
	SaveBinaryData(ctx context.Context, in *SaveBinaryDataRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error)
	Delete(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
}

type privateDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivateDataServiceClient(cc grpc.ClientConnInterface) PrivateDataServiceClient {
	return &privateDataServiceClient{cc}
}

func (c *privateDataServiceClient) SaveLoginPassword(ctx context.Context, in *SaveLoginPasswordRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedDataResponse)
	err := c.cc.Invoke(ctx, PrivateDataService_SaveLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateDataServiceClient) SaveBankCard(ctx context.Context, in *SaveBankCardRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedDataResponse)
	err := c.cc.Invoke(ctx, PrivateDataService_SaveBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateDataServiceClient) SaveTextData(ctx context.Context, in *SaveTextDataRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedDataResponse)
	err := c.cc.Invoke(ctx, PrivateDataService_SaveTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateDataServiceClient) SaveBinaryData(ctx context.Context, in *SaveBinaryDataRequest, opts ...grpc.CallOption) (*EncryptedDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedDataResponse)
	err := c.cc.Invoke(ctx, PrivateDataService_SaveBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateDataServiceClient) Delete(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, PrivateDataService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateDataServiceServer is the server API for PrivateDataService service.
// All implementations must embed UnimplementedPrivateDataServiceServer
// for forward compatibility.
type PrivateDataServiceServer interface {
	SaveLoginPassword(context.Context, *SaveLoginPasswordRequest) (*EncryptedDataResponse, error)
	SaveBankCard(context.Context, *SaveBankCardRequest) (*EncryptedDataResponse, error)
	SaveTextData(context.Context, *SaveTextDataRequest) (*EncryptedDataResponse, error)
	SaveBinaryData(context.Context, *SaveBinaryDataRequest) (*EncryptedDataResponse, error)
	Delete(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
	mustEmbedUnimplementedPrivateDataServiceServer()
}

// UnimplementedPrivateDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivateDataServiceServer struct{}

func (UnimplementedPrivateDataServiceServer) SaveLoginPassword(context.Context, *SaveLoginPasswordRequest) (*EncryptedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLoginPassword not implemented")
}
func (UnimplementedPrivateDataServiceServer) SaveBankCard(context.Context, *SaveBankCardRequest) (*EncryptedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBankCard not implemented")
}
func (UnimplementedPrivateDataServiceServer) SaveTextData(context.Context, *SaveTextDataRequest) (*EncryptedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTextData not implemented")
}
func (UnimplementedPrivateDataServiceServer) SaveBinaryData(context.Context, *SaveBinaryDataRequest) (*EncryptedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBinaryData not implemented")
}
func (UnimplementedPrivateDataServiceServer) Delete(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPrivateDataServiceServer) mustEmbedUnimplementedPrivateDataServiceServer() {}
func (UnimplementedPrivateDataServiceServer) testEmbeddedByValue()                            {}

// UnsafePrivateDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivateDataServiceServer will
// result in compilation errors.
type UnsafePrivateDataServiceServer interface {
	mustEmbedUnimplementedPrivateDataServiceServer()
}

func RegisterPrivateDataServiceServer(s grpc.ServiceRegistrar, srv PrivateDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrivateDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivateDataService_ServiceDesc, srv)
}

func _PrivateDataService_SaveLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLoginPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateDataServiceServer).SaveLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateDataService_SaveLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateDataServiceServer).SaveLoginPassword(ctx, req.(*SaveLoginPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateDataService_SaveBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBankCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateDataServiceServer).SaveBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateDataService_SaveBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateDataServiceServer).SaveBankCard(ctx, req.(*SaveBankCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateDataService_SaveTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateDataServiceServer).SaveTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateDataService_SaveTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateDataServiceServer).SaveTextData(ctx, req.(*SaveTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateDataService_SaveBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBinaryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateDataServiceServer).SaveBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateDataService_SaveBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateDataServiceServer).SaveBinaryData(ctx, req.(*SaveBinaryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateDataService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateDataServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateDataService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateDataServiceServer).Delete(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivateDataService_ServiceDesc is the grpc.ServiceDesc for PrivateDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivateDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PrivateDataService",
	HandlerType: (*PrivateDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveLoginPassword",
			Handler:    _PrivateDataService_SaveLoginPassword_Handler,
		},
		{
			MethodName: "SaveBankCard",
			Handler:    _PrivateDataService_SaveBankCard_Handler,
		},
		{
			MethodName: "SaveTextData",
			Handler:    _PrivateDataService_SaveTextData_Handler,
		},
		{
			MethodName: "SaveBinaryData",
			Handler:    _PrivateDataService_SaveBinaryData_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PrivateDataService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
