// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ConfirmAssess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmAssess) Reset() {
	*x = ConfirmAssess{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmAssess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmAssess) ProtoMessage() {}

func (x *ConfirmAssess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmAssess.ProtoReflect.Descriptor instead.
func (*ConfirmAssess) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmAssess) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EncryptedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Dek           []byte                 `protobuf:"bytes,3,opt,name=dek,proto3" json:"dek,omitempty"`
	Metadata      []*Metadata            `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptedData) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *EncryptedData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncryptedData) GetDek() []byte {
	if x != nil {
		return x.Dek
	}
	return nil
}

func (x *EncryptedData) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadata) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EncryptedDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *EncryptedData         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDataResponse) Reset() {
	*x = EncryptedDataResponse{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDataResponse) ProtoMessage() {}

func (x *EncryptedDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDataResponse.ProtoReflect.Descriptor instead.
func (*EncryptedDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *EncryptedDataResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EncryptedDataResponse) GetData() *EncryptedData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncryptedDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Credential    *ConfirmAssess         `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteDataRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DeleteDataRequest) GetCredential() *ConfirmAssess {
	if x != nil {
		return x.Credential
	}
	return nil
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Credential    *ConfirmAssess         `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDataRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetDataRequest) GetCredential() *ConfirmAssess {
	if x != nil {
		return x.Credential
	}
	return nil
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*EncryptedData       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetDataResponse) GetData() []*EncryptedData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SaveLoginPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Credential    *ConfirmAssess         `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLoginPasswordRequest) Reset() {
	*x = SaveLoginPasswordRequest{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLoginPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLoginPasswordRequest) ProtoMessage() {}

func (x *SaveLoginPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLoginPasswordRequest.ProtoReflect.Descriptor instead.
func (*SaveLoginPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *SaveLoginPasswordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveLoginPasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SaveLoginPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SaveLoginPasswordRequest) GetCredential() *ConfirmAssess {
	if x != nil {
		return x.Credential
	}
	return nil
}

type SaveBankCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Expires       string                 `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	Cvv           int64                  `protobuf:"varint,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Credential    *ConfirmAssess         `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBankCardRequest) Reset() {
	*x = SaveBankCardRequest{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBankCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBankCardRequest) ProtoMessage() {}

func (x *SaveBankCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBankCardRequest.ProtoReflect.Descriptor instead.
func (*SaveBankCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *SaveBankCardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveBankCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *SaveBankCardRequest) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *SaveBankCardRequest) GetCvv() int64 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

func (x *SaveBankCardRequest) GetCredential() *ConfirmAssess {
	if x != nil {
		return x.Credential
	}
	return nil
}

type SaveTextDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Credential    *ConfirmAssess         `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTextDataRequest) Reset() {
	*x = SaveTextDataRequest{}
	mi := &file_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTextDataRequest) ProtoMessage() {}

func (x *SaveTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTextDataRequest.ProtoReflect.Descriptor instead.
func (*SaveTextDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *SaveTextDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveTextDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveTextDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SaveTextDataRequest) GetCredential() *ConfirmAssess {
	if x != nil {
		return x.Credential
	}
	return nil
}

type SaveBinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Credential    *ConfirmAssess         `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBinaryDataRequest) Reset() {
	*x = SaveBinaryDataRequest{}
	mi := &file_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBinaryDataRequest) ProtoMessage() {}

func (x *SaveBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*SaveBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *SaveBinaryDataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveBinaryDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveBinaryDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SaveBinaryDataRequest) GetCredential() *ConfirmAssess {
	if x != nil {
		return x.Credential
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"H\n" +
	"\x14CreateAccountRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rConfirmAssess\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x15CreateAccountResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"_\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\";\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"\rEncryptedData\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03dek\x18\x03 \x01(\fR\x03dek\x12+\n" +
	"\bmetadata\x18\x04 \x03(\v2\x0f.proto.MetadataR\bmetadata\"2\n" +
	"\bMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"g\n" +
	"\x15EncryptedDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.proto.EncryptedDataR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"m\n" +
	"\x11DeleteDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x124\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2\x14.proto.ConfirmAssessR\n" +
	"credential\"*\n" +
	"\x12DeleteDataResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"j\n" +
	"\x0eGetDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x124\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2\x14.proto.ConfirmAssessR\n" +
	"credential\"Q\n" +
	"\x0fGetDataResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.proto.EncryptedDataR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x92\x01\n" +
	"\x18SaveLoginPasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x124\n" +
	"\n" +
	"credential\x18\x04 \x01(\v2\x14.proto.ConfirmAssessR\n" +
	"credential\"\x9f\x01\n" +
	"\x13SaveBankCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\tR\aexpires\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\x03R\x03cvv\x124\n" +
	"\n" +
	"credential\x18\x05 \x01(\v2\x14.proto.ConfirmAssessR\n" +
	"credential\"\x83\x01\n" +
	"\x13SaveTextDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x124\n" +
	"\n" +
	"credential\x18\x04 \x01(\v2\x14.proto.ConfirmAssessR\n" +
	"credential\"\x85\x01\n" +
	"\x15SaveBinaryDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x124\n" +
	"\n" +
	"credential\x18\x04 \x01(\v2\x14.proto.ConfirmAssessR\n" +
	"credential2\x94\x01\n" +
	"\x0eAccountService\x12L\n" +
	"\rCreateAccount\x12\x1b.proto.CreateAccountRequest\x1a\x1c.proto.CreateAccountResponse\"\x00\x124\n" +
	"\x05Login\x12\x13.proto.LoginRequest\x1a\x14.proto.LoginResponse\"\x002\xcb\x03\n" +
	"\x12PrivateDataService\x12T\n" +
	"\x11SaveLoginPassword\x12\x1f.proto.SaveLoginPasswordRequest\x1a\x1c.proto.EncryptedDataResponse\"\x00\x12J\n" +
	"\fSaveBankCard\x12\x1a.proto.SaveBankCardRequest\x1a\x1c.proto.EncryptedDataResponse\"\x00\x12J\n" +
	"\fSaveTextData\x12\x1a.proto.SaveTextDataRequest\x1a\x1c.proto.EncryptedDataResponse\"\x00\x12N\n" +
	"\x0eSaveBinaryData\x12\x1c.proto.SaveBinaryDataRequest\x1a\x1c.proto.EncryptedDataResponse\"\x00\x126\n" +
	"\x03Get\x12\x15.proto.GetDataRequest\x1a\x16.proto.GetDataResponse\"\x00\x12?\n" +
	"\x06Delete\x12\x18.proto.DeleteDataRequest\x1a\x19.proto.DeleteDataResponse\"\x00B!Z\x1fgithub.com/vilasle/gokeep/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),     // 0: proto.CreateAccountRequest
	(*ConfirmAssess)(nil),            // 1: proto.ConfirmAssess
	(*CreateAccountResponse)(nil),    // 2: proto.CreateAccountResponse
	(*LoginRequest)(nil),             // 3: proto.LoginRequest
	(*LoginResponse)(nil),            // 4: proto.LoginResponse
	(*EncryptedData)(nil),            // 5: proto.EncryptedData
	(*Metadata)(nil),                 // 6: proto.Metadata
	(*EncryptedDataResponse)(nil),    // 7: proto.EncryptedDataResponse
	(*DeleteDataRequest)(nil),        // 8: proto.DeleteDataRequest
	(*DeleteDataResponse)(nil),       // 9: proto.DeleteDataResponse
	(*GetDataRequest)(nil),           // 10: proto.GetDataRequest
	(*GetDataResponse)(nil),          // 11: proto.GetDataResponse
	(*SaveLoginPasswordRequest)(nil), // 12: proto.SaveLoginPasswordRequest
	(*SaveBankCardRequest)(nil),      // 13: proto.SaveBankCardRequest
	(*SaveTextDataRequest)(nil),      // 14: proto.SaveTextDataRequest
	(*SaveBinaryDataRequest)(nil),    // 15: proto.SaveBinaryDataRequest
}
var file_proto_service_proto_depIdxs = []int32{
	6,  // 0: proto.EncryptedData.metadata:type_name -> proto.Metadata
	5,  // 1: proto.EncryptedDataResponse.data:type_name -> proto.EncryptedData
	1,  // 2: proto.DeleteDataRequest.credential:type_name -> proto.ConfirmAssess
	1,  // 3: proto.GetDataRequest.credential:type_name -> proto.ConfirmAssess
	5,  // 4: proto.GetDataResponse.data:type_name -> proto.EncryptedData
	1,  // 5: proto.SaveLoginPasswordRequest.credential:type_name -> proto.ConfirmAssess
	1,  // 6: proto.SaveBankCardRequest.credential:type_name -> proto.ConfirmAssess
	1,  // 7: proto.SaveTextDataRequest.credential:type_name -> proto.ConfirmAssess
	1,  // 8: proto.SaveBinaryDataRequest.credential:type_name -> proto.ConfirmAssess
	0,  // 9: proto.AccountService.CreateAccount:input_type -> proto.CreateAccountRequest
	3,  // 10: proto.AccountService.Login:input_type -> proto.LoginRequest
	12, // 11: proto.PrivateDataService.SaveLoginPassword:input_type -> proto.SaveLoginPasswordRequest
	13, // 12: proto.PrivateDataService.SaveBankCard:input_type -> proto.SaveBankCardRequest
	14, // 13: proto.PrivateDataService.SaveTextData:input_type -> proto.SaveTextDataRequest
	15, // 14: proto.PrivateDataService.SaveBinaryData:input_type -> proto.SaveBinaryDataRequest
	10, // 15: proto.PrivateDataService.Get:input_type -> proto.GetDataRequest
	8,  // 16: proto.PrivateDataService.Delete:input_type -> proto.DeleteDataRequest
	2,  // 17: proto.AccountService.CreateAccount:output_type -> proto.CreateAccountResponse
	4,  // 18: proto.AccountService.Login:output_type -> proto.LoginResponse
	7,  // 19: proto.PrivateDataService.SaveLoginPassword:output_type -> proto.EncryptedDataResponse
	7,  // 20: proto.PrivateDataService.SaveBankCard:output_type -> proto.EncryptedDataResponse
	7,  // 21: proto.PrivateDataService.SaveTextData:output_type -> proto.EncryptedDataResponse
	7,  // 22: proto.PrivateDataService.SaveBinaryData:output_type -> proto.EncryptedDataResponse
	11, // 23: proto.PrivateDataService.Get:output_type -> proto.GetDataResponse
	9,  // 24: proto.PrivateDataService.Delete:output_type -> proto.DeleteDataResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
