// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/client/repository.go

// Package cli is a generated GoMock package.
package cli

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vilasle/gokeep/internal/model"
	client "github.com/vilasle/gokeep/internal/repository/client"
)

// MockClientRepository is a mock of ClientRepository interface.
type MockClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientRepositoryMockRecorder
}

// MockClientRepositoryMockRecorder is the mock recorder for MockClientRepository.
type MockClientRepositoryMockRecorder struct {
	mock *MockClientRepository
}

// NewMockClientRepository creates a new mock instance.
func NewMockClientRepository(ctrl *gomock.Controller) *MockClientRepository {
	mock := &MockClientRepository{ctrl: ctrl}
	mock.recorder = &MockClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRepository) EXPECT() *MockClientRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockClientRepository) All(ctx context.Context, tData model.Type) ([]client.GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, tData)
	ret0, _ := ret[0].([]client.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockClientRepositoryMockRecorder) All(ctx, tData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockClientRepository)(nil).All), ctx, tData)
}

// Close mocks base method.
func (m *MockClientRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientRepository)(nil).Close))
}

// CreateScheme mocks base method.
func (m *MockClientRepository) CreateScheme(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheme", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScheme indicates an expected call of CreateScheme.
func (mr *MockClientRepositoryMockRecorder) CreateScheme(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheme", reflect.TypeOf((*MockClientRepository)(nil).CreateScheme), ctx)
}

// Delete mocks base method.
func (m *MockClientRepository) Delete(ctx context.Context, req client.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientRepositoryMockRecorder) Delete(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientRepository)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockClientRepository) Get(ctx context.Context, req client.GetRequest) ([]client.GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].([]client.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientRepositoryMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientRepository)(nil).Get), ctx, req)
}

// Rewrite mocks base method.
func (m *MockClientRepository) Rewrite(ctx context.Context, req []client.SaveRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rewrite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rewrite indicates an expected call of Rewrite.
func (mr *MockClientRepositoryMockRecorder) Rewrite(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rewrite", reflect.TypeOf((*MockClientRepository)(nil).Rewrite), ctx, req)
}

// Save mocks base method.
func (m *MockClientRepository) Save(ctx context.Context, req client.SaveRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockClientRepositoryMockRecorder) Save(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockClientRepository)(nil).Save), ctx, req)
}
