// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/client/service.go

// Package cli is a generated GoMock package.
package cli

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "github.com/vilasle/gokeep/internal/service/client"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAuthService) CreateAccount(ctx context.Context, accountName, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, accountName, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAuthServiceMockRecorder) CreateAccount(ctx, accountName, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAuthService)(nil).CreateAccount), ctx, accountName, password)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, accountName, password string, publicKey []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, accountName, password, publicKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, accountName, password, publicKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, accountName, password, publicKey)
}

// MockLoginPasswordDataService is a mock of LoginPasswordDataService interface.
type MockLoginPasswordDataService struct {
	ctrl     *gomock.Controller
	recorder *MockLoginPasswordDataServiceMockRecorder
}

// MockLoginPasswordDataServiceMockRecorder is the mock recorder for MockLoginPasswordDataService.
type MockLoginPasswordDataServiceMockRecorder struct {
	mock *MockLoginPasswordDataService
}

// NewMockLoginPasswordDataService creates a new mock instance.
func NewMockLoginPasswordDataService(ctrl *gomock.Controller) *MockLoginPasswordDataService {
	mock := &MockLoginPasswordDataService{ctrl: ctrl}
	mock.recorder = &MockLoginPasswordDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginPasswordDataService) EXPECT() *MockLoginPasswordDataServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLoginPasswordDataService) Delete(arg0 context.Context, arg1 client.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLoginPasswordDataServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoginPasswordDataService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockLoginPasswordDataService) Get(arg0 context.Context, arg1 client.GetRequest) ([]client.EncryptedEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].([]client.EncryptedEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLoginPasswordDataServiceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLoginPasswordDataService)(nil).Get), arg0, arg1)
}

// Save mocks base method.
func (m *MockLoginPasswordDataService) Save(arg0 context.Context, arg1 client.LoginPasswordSaveRequest) (client.SaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(client.SaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockLoginPasswordDataServiceMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLoginPasswordDataService)(nil).Save), arg0, arg1)
}

// MockBankCardDataService is a mock of BankCardDataService interface.
type MockBankCardDataService struct {
	ctrl     *gomock.Controller
	recorder *MockBankCardDataServiceMockRecorder
}

// MockBankCardDataServiceMockRecorder is the mock recorder for MockBankCardDataService.
type MockBankCardDataServiceMockRecorder struct {
	mock *MockBankCardDataService
}

// NewMockBankCardDataService creates a new mock instance.
func NewMockBankCardDataService(ctrl *gomock.Controller) *MockBankCardDataService {
	mock := &MockBankCardDataService{ctrl: ctrl}
	mock.recorder = &MockBankCardDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankCardDataService) EXPECT() *MockBankCardDataServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBankCardDataService) Delete(arg0 context.Context, arg1 client.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBankCardDataServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBankCardDataService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockBankCardDataService) Get(arg0 context.Context, arg1 client.GetRequest) ([]client.EncryptedEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].([]client.EncryptedEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBankCardDataServiceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBankCardDataService)(nil).Get), arg0, arg1)
}

// Save mocks base method.
func (m *MockBankCardDataService) Save(arg0 context.Context, arg1 client.BankCardSaveRequest) (client.SaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(client.SaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockBankCardDataServiceMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBankCardDataService)(nil).Save), arg0, arg1)
}

// MockTextDataDataService is a mock of TextDataDataService interface.
type MockTextDataDataService struct {
	ctrl     *gomock.Controller
	recorder *MockTextDataDataServiceMockRecorder
}

// MockTextDataDataServiceMockRecorder is the mock recorder for MockTextDataDataService.
type MockTextDataDataServiceMockRecorder struct {
	mock *MockTextDataDataService
}

// NewMockTextDataDataService creates a new mock instance.
func NewMockTextDataDataService(ctrl *gomock.Controller) *MockTextDataDataService {
	mock := &MockTextDataDataService{ctrl: ctrl}
	mock.recorder = &MockTextDataDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextDataDataService) EXPECT() *MockTextDataDataServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTextDataDataService) Delete(arg0 context.Context, arg1 client.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTextDataDataServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTextDataDataService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockTextDataDataService) Get(arg0 context.Context, arg1 client.GetRequest) ([]client.EncryptedEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].([]client.EncryptedEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTextDataDataServiceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTextDataDataService)(nil).Get), arg0, arg1)
}

// Save mocks base method.
func (m *MockTextDataDataService) Save(arg0 context.Context, arg1 client.TextDataSaveRequest) (client.SaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(client.SaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockTextDataDataServiceMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTextDataDataService)(nil).Save), arg0, arg1)
}

// MockBinaryDataDataService is a mock of BinaryDataDataService interface.
type MockBinaryDataDataService struct {
	ctrl     *gomock.Controller
	recorder *MockBinaryDataDataServiceMockRecorder
}

// MockBinaryDataDataServiceMockRecorder is the mock recorder for MockBinaryDataDataService.
type MockBinaryDataDataServiceMockRecorder struct {
	mock *MockBinaryDataDataService
}

// NewMockBinaryDataDataService creates a new mock instance.
func NewMockBinaryDataDataService(ctrl *gomock.Controller) *MockBinaryDataDataService {
	mock := &MockBinaryDataDataService{ctrl: ctrl}
	mock.recorder = &MockBinaryDataDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinaryDataDataService) EXPECT() *MockBinaryDataDataServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBinaryDataDataService) Delete(arg0 context.Context, arg1 client.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBinaryDataDataServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBinaryDataDataService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockBinaryDataDataService) Get(arg0 context.Context, arg1 client.GetRequest) ([]client.EncryptedEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].([]client.EncryptedEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBinaryDataDataServiceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBinaryDataDataService)(nil).Get), arg0, arg1)
}

// Save mocks base method.
func (m *MockBinaryDataDataService) Save(arg0 context.Context, arg1 client.BinaryDataSaveRequest) (client.SaveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(client.SaveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockBinaryDataDataServiceMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBinaryDataDataService)(nil).Save), arg0, arg1)
}
