// Code generated by MockGen. DO NOT EDIT.
// Source: proto/service_grpc.pb.go

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/vilasle/gokeep/proto"
	grpc "google.golang.org/grpc"
)

// MockAccountServiceClient is a mock of AccountServiceClient interface.
type MockAccountServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceClientMockRecorder
}

// MockAccountServiceClientMockRecorder is the mock recorder for MockAccountServiceClient.
type MockAccountServiceClientMockRecorder struct {
	mock *MockAccountServiceClient
}

// NewMockAccountServiceClient creates a new mock instance.
func NewMockAccountServiceClient(ctrl *gomock.Controller) *MockAccountServiceClient {
	mock := &MockAccountServiceClient{ctrl: ctrl}
	mock.recorder = &MockAccountServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountServiceClient) EXPECT() *MockAccountServiceClientMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountServiceClient) CreateAccount(ctx context.Context, in *proto.CreateAccountRequest, opts ...grpc.CallOption) (*proto.CreateAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAccount", varargs...)
	ret0, _ := ret[0].(*proto.CreateAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountServiceClientMockRecorder) CreateAccount(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountServiceClient)(nil).CreateAccount), varargs...)
}

// Login mocks base method.
func (m *MockAccountServiceClient) Login(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*proto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAccountServiceClientMockRecorder) Login(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAccountServiceClient)(nil).Login), varargs...)
}

// MockAccountServiceServer is a mock of AccountServiceServer interface.
type MockAccountServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceServerMockRecorder
}

// MockAccountServiceServerMockRecorder is the mock recorder for MockAccountServiceServer.
type MockAccountServiceServerMockRecorder struct {
	mock *MockAccountServiceServer
}

// NewMockAccountServiceServer creates a new mock instance.
func NewMockAccountServiceServer(ctrl *gomock.Controller) *MockAccountServiceServer {
	mock := &MockAccountServiceServer{ctrl: ctrl}
	mock.recorder = &MockAccountServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountServiceServer) EXPECT() *MockAccountServiceServerMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountServiceServer) CreateAccount(arg0 context.Context, arg1 *proto.CreateAccountRequest) (*proto.CreateAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", arg0, arg1)
	ret0, _ := ret[0].(*proto.CreateAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountServiceServerMockRecorder) CreateAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountServiceServer)(nil).CreateAccount), arg0, arg1)
}

// Login mocks base method.
func (m *MockAccountServiceServer) Login(arg0 context.Context, arg1 *proto.LoginRequest) (*proto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*proto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAccountServiceServerMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAccountServiceServer)(nil).Login), arg0, arg1)
}

// mustEmbedUnimplementedAccountServiceServer mocks base method.
func (m *MockAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAccountServiceServer")
}

// mustEmbedUnimplementedAccountServiceServer indicates an expected call of mustEmbedUnimplementedAccountServiceServer.
func (mr *MockAccountServiceServerMockRecorder) mustEmbedUnimplementedAccountServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAccountServiceServer", reflect.TypeOf((*MockAccountServiceServer)(nil).mustEmbedUnimplementedAccountServiceServer))
}

// MockUnsafeAccountServiceServer is a mock of UnsafeAccountServiceServer interface.
type MockUnsafeAccountServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeAccountServiceServerMockRecorder
}

// MockUnsafeAccountServiceServerMockRecorder is the mock recorder for MockUnsafeAccountServiceServer.
type MockUnsafeAccountServiceServerMockRecorder struct {
	mock *MockUnsafeAccountServiceServer
}

// NewMockUnsafeAccountServiceServer creates a new mock instance.
func NewMockUnsafeAccountServiceServer(ctrl *gomock.Controller) *MockUnsafeAccountServiceServer {
	mock := &MockUnsafeAccountServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeAccountServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeAccountServiceServer) EXPECT() *MockUnsafeAccountServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedAccountServiceServer mocks base method.
func (m *MockUnsafeAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAccountServiceServer")
}

// mustEmbedUnimplementedAccountServiceServer indicates an expected call of mustEmbedUnimplementedAccountServiceServer.
func (mr *MockUnsafeAccountServiceServerMockRecorder) mustEmbedUnimplementedAccountServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAccountServiceServer", reflect.TypeOf((*MockUnsafeAccountServiceServer)(nil).mustEmbedUnimplementedAccountServiceServer))
}

// MockPrivateDataServiceClient is a mock of PrivateDataServiceClient interface.
type MockPrivateDataServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataServiceClientMockRecorder
}

// MockPrivateDataServiceClientMockRecorder is the mock recorder for MockPrivateDataServiceClient.
type MockPrivateDataServiceClientMockRecorder struct {
	mock *MockPrivateDataServiceClient
}

// NewMockPrivateDataServiceClient creates a new mock instance.
func NewMockPrivateDataServiceClient(ctrl *gomock.Controller) *MockPrivateDataServiceClient {
	mock := &MockPrivateDataServiceClient{ctrl: ctrl}
	mock.recorder = &MockPrivateDataServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataServiceClient) EXPECT() *MockPrivateDataServiceClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPrivateDataServiceClient) Delete(ctx context.Context, in *proto.DeleteDataRequest, opts ...grpc.CallOption) (*proto.DeleteDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*proto.DeleteDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPrivateDataServiceClientMockRecorder) Delete(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrivateDataServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockPrivateDataServiceClient) Get(ctx context.Context, in *proto.GetDataRequest, opts ...grpc.CallOption) (*proto.GetDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*proto.GetDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPrivateDataServiceClientMockRecorder) Get(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrivateDataServiceClient)(nil).Get), varargs...)
}

// SaveBankCard mocks base method.
func (m *MockPrivateDataServiceClient) SaveBankCard(ctx context.Context, in *proto.SaveBankCardRequest, opts ...grpc.CallOption) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveBankCard", varargs...)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBankCard indicates an expected call of SaveBankCard.
func (mr *MockPrivateDataServiceClientMockRecorder) SaveBankCard(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBankCard", reflect.TypeOf((*MockPrivateDataServiceClient)(nil).SaveBankCard), varargs...)
}

// SaveBinaryData mocks base method.
func (m *MockPrivateDataServiceClient) SaveBinaryData(ctx context.Context, in *proto.SaveBinaryDataRequest, opts ...grpc.CallOption) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveBinaryData", varargs...)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBinaryData indicates an expected call of SaveBinaryData.
func (mr *MockPrivateDataServiceClientMockRecorder) SaveBinaryData(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBinaryData", reflect.TypeOf((*MockPrivateDataServiceClient)(nil).SaveBinaryData), varargs...)
}

// SaveLoginPassword mocks base method.
func (m *MockPrivateDataServiceClient) SaveLoginPassword(ctx context.Context, in *proto.SaveLoginPasswordRequest, opts ...grpc.CallOption) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveLoginPassword", varargs...)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveLoginPassword indicates an expected call of SaveLoginPassword.
func (mr *MockPrivateDataServiceClientMockRecorder) SaveLoginPassword(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLoginPassword", reflect.TypeOf((*MockPrivateDataServiceClient)(nil).SaveLoginPassword), varargs...)
}

// SaveTextData mocks base method.
func (m *MockPrivateDataServiceClient) SaveTextData(ctx context.Context, in *proto.SaveTextDataRequest, opts ...grpc.CallOption) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveTextData", varargs...)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTextData indicates an expected call of SaveTextData.
func (mr *MockPrivateDataServiceClientMockRecorder) SaveTextData(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTextData", reflect.TypeOf((*MockPrivateDataServiceClient)(nil).SaveTextData), varargs...)
}

// MockPrivateDataServiceServer is a mock of PrivateDataServiceServer interface.
type MockPrivateDataServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataServiceServerMockRecorder
}

// MockPrivateDataServiceServerMockRecorder is the mock recorder for MockPrivateDataServiceServer.
type MockPrivateDataServiceServerMockRecorder struct {
	mock *MockPrivateDataServiceServer
}

// NewMockPrivateDataServiceServer creates a new mock instance.
func NewMockPrivateDataServiceServer(ctrl *gomock.Controller) *MockPrivateDataServiceServer {
	mock := &MockPrivateDataServiceServer{ctrl: ctrl}
	mock.recorder = &MockPrivateDataServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataServiceServer) EXPECT() *MockPrivateDataServiceServerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPrivateDataServiceServer) Delete(arg0 context.Context, arg1 *proto.DeleteDataRequest) (*proto.DeleteDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPrivateDataServiceServerMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockPrivateDataServiceServer) Get(arg0 context.Context, arg1 *proto.GetDataRequest) (*proto.GetDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPrivateDataServiceServerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).Get), arg0, arg1)
}

// SaveBankCard mocks base method.
func (m *MockPrivateDataServiceServer) SaveBankCard(arg0 context.Context, arg1 *proto.SaveBankCardRequest) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBankCard", arg0, arg1)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBankCard indicates an expected call of SaveBankCard.
func (mr *MockPrivateDataServiceServerMockRecorder) SaveBankCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBankCard", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).SaveBankCard), arg0, arg1)
}

// SaveBinaryData mocks base method.
func (m *MockPrivateDataServiceServer) SaveBinaryData(arg0 context.Context, arg1 *proto.SaveBinaryDataRequest) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBinaryData", arg0, arg1)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBinaryData indicates an expected call of SaveBinaryData.
func (mr *MockPrivateDataServiceServerMockRecorder) SaveBinaryData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBinaryData", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).SaveBinaryData), arg0, arg1)
}

// SaveLoginPassword mocks base method.
func (m *MockPrivateDataServiceServer) SaveLoginPassword(arg0 context.Context, arg1 *proto.SaveLoginPasswordRequest) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLoginPassword", arg0, arg1)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveLoginPassword indicates an expected call of SaveLoginPassword.
func (mr *MockPrivateDataServiceServerMockRecorder) SaveLoginPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLoginPassword", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).SaveLoginPassword), arg0, arg1)
}

// SaveTextData mocks base method.
func (m *MockPrivateDataServiceServer) SaveTextData(arg0 context.Context, arg1 *proto.SaveTextDataRequest) (*proto.EncryptedDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTextData", arg0, arg1)
	ret0, _ := ret[0].(*proto.EncryptedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTextData indicates an expected call of SaveTextData.
func (mr *MockPrivateDataServiceServerMockRecorder) SaveTextData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTextData", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).SaveTextData), arg0, arg1)
}

// mustEmbedUnimplementedPrivateDataServiceServer mocks base method.
func (m *MockPrivateDataServiceServer) mustEmbedUnimplementedPrivateDataServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPrivateDataServiceServer")
}

// mustEmbedUnimplementedPrivateDataServiceServer indicates an expected call of mustEmbedUnimplementedPrivateDataServiceServer.
func (mr *MockPrivateDataServiceServerMockRecorder) mustEmbedUnimplementedPrivateDataServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPrivateDataServiceServer", reflect.TypeOf((*MockPrivateDataServiceServer)(nil).mustEmbedUnimplementedPrivateDataServiceServer))
}

// MockUnsafePrivateDataServiceServer is a mock of UnsafePrivateDataServiceServer interface.
type MockUnsafePrivateDataServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafePrivateDataServiceServerMockRecorder
}

// MockUnsafePrivateDataServiceServerMockRecorder is the mock recorder for MockUnsafePrivateDataServiceServer.
type MockUnsafePrivateDataServiceServerMockRecorder struct {
	mock *MockUnsafePrivateDataServiceServer
}

// NewMockUnsafePrivateDataServiceServer creates a new mock instance.
func NewMockUnsafePrivateDataServiceServer(ctrl *gomock.Controller) *MockUnsafePrivateDataServiceServer {
	mock := &MockUnsafePrivateDataServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafePrivateDataServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafePrivateDataServiceServer) EXPECT() *MockUnsafePrivateDataServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedPrivateDataServiceServer mocks base method.
func (m *MockUnsafePrivateDataServiceServer) mustEmbedUnimplementedPrivateDataServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPrivateDataServiceServer")
}

// mustEmbedUnimplementedPrivateDataServiceServer indicates an expected call of mustEmbedUnimplementedPrivateDataServiceServer.
func (mr *MockUnsafePrivateDataServiceServerMockRecorder) mustEmbedUnimplementedPrivateDataServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPrivateDataServiceServer", reflect.TypeOf((*MockUnsafePrivateDataServiceServer)(nil).mustEmbedUnimplementedPrivateDataServiceServer))
}
